package net.lootr.serveronly.config;

import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.storage.loot.LootTable;
import net.neoforged.neoforge.common.ModConfigSpec;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Server config (COMMON type, so it lives in the world's serverconfig-adjacent
 * {@code config/lootr_serveronly-common.toml}). Deliberately small - see the
 * design doc §6: team loot, dimension whitelist/blacklist, refresh timer.
 */
public final class LootrConfig {
    private static final ModConfigSpec.Builder BUILDER = new ModConfigSpec.Builder();

    public static final ModConfigSpec.BooleanValue TEAM_LOOT;
    public static final ModConfigSpec.ConfigValue<List<? extends String>> DIMENSION_WHITELIST;
    public static final ModConfigSpec.ConfigValue<List<? extends String>> DIMENSION_BLACKLIST;
    public static final ModConfigSpec.ConfigValue<List<? extends String>> LOOT_TABLE_BLACKLIST;
    public static final ModConfigSpec.ConfigValue<List<? extends String>> MOD_ID_BLACKLIST;
    public static final ModConfigSpec.IntValue REFRESH_TICKS;
    public static final ModConfigSpec.BooleanValue CONVERT_ITEM_FRAMES;
    public static final ModConfigSpec.BooleanValue CONVERT_ELYTRAS_TO_ITEM_FRAMES;
    public static final ModConfigSpec.BooleanValue PROTECT_CONTAINERS;
    public static final ModConfigSpec.BooleanValue BREAK_TO_DROP_LOOT;
    public static final ModConfigSpec.BooleanValue REQUIRE_SNEAK_TO_BREAK;
    public static final ModConfigSpec.BooleanValue SHOULD_DROP_PLAYER_LOOT;

    public static final ModConfigSpec SPEC;

    static {
        BUILDER.push("team");
        TEAM_LOOT = BUILDER
                .comment("If true, loot is shared per scoreboard team instead of per player.",
                        "Players not on a team are treated as a team of one.")
                .define("team_loot", false);
        BUILDER.pop();

        BUILDER.push("dimensions");
        DIMENSION_WHITELIST = BUILDER
                .comment("If non-empty, containers only convert to per-player loot in these dimensions (e.g. \"minecraft:overworld\").")
                .defineListAllowEmpty("dimension_whitelist", List.of(), () -> "minecraft:overworld", o -> o instanceof String);
        DIMENSION_BLACKLIST = BUILDER
                .comment("Containers in these dimensions are never converted. Takes priority over the whitelist.")
                .defineListAllowEmpty("dimension_blacklist", List.of(), () -> "minecraft:the_end", o -> o instanceof String);
        BUILDER.pop();

        BUILDER.push("loot_filters");
        LOOT_TABLE_BLACKLIST = BUILDER
                .comment("Loot tables that are never converted. Containers using them behave exactly like vanilla.",
                        "Exact ids, e.g. \"minecraft:chests/spawn_bonus_chest\".")
                .defineListAllowEmpty("loot_table_blacklist", List.of(), () -> "minecraft:chests/spawn_bonus_chest", o -> o instanceof String);
        MOD_ID_BLACKLIST = BUILDER
                .comment("Namespaces whose loot tables are never converted, e.g. \"somemod\" covers every \"somemod:...\" table.")
                .defineListAllowEmpty("mod_id_blacklist", List.of(), () -> "somemod", o -> o instanceof String);
        BUILDER.pop();

        BUILDER.push("refresh");
        REFRESH_TICKS = BUILDER
                .comment("Ticks after a container is first looted before it resets for everyone. 0 disables refreshing.",
                        "Checked when a player opens the container, not in the background.")
                .defineInRange("refresh_ticks", 0, 0, Integer.MAX_VALUE);
        BUILDER.pop();

        // The two key names below deliberately match upstream Lootr's own
        // config keys so an admin migrating from it can copy their values.
        // (Upstream "converts" a frame into a different entity type; this mod
        // cannot, so it MARKS the vanilla frame instead - see ItemFrameMarker.)
        BUILDER.push("item_frames");
        CONVERT_ITEM_FRAMES = BUILDER
                .comment("If true, item frames that hold an item and are generated by a structure (vanilla, datapack or modded)",
                        "become Lootr frames: each player (or team) can take one copy of the framed item by hitting the frame.",
                        "Never applied to fixed frames, invisible frames, empty frames, or frames holding a map.",
                        "Only affects frames generated AFTER this is enabled. Existing frames can be marked by hand - see ItemFrameMarker.")
                .define("convert_item_frames", true);
        CONVERT_ELYTRAS_TO_ITEM_FRAMES = BUILDER
                .comment("If true, the Elytra item frame on End City ships becomes a Lootr frame.",
                        "Only affects End cities generated AFTER this is enabled.")
                .define("convert_elytras_to_item_frames", true);
        BUILDER.pop();

        BUILDER.push("protection");
        PROTECT_CONTAINERS = BUILDER
                .comment("If true, survival players cannot break loot containers and explosions leave them standing,",
                        "so one player can't destroy the loot for everyone. Also makes loot pots immune to projectiles",
                        "and marked item frames / loot chest minecarts immune to arrows, explosions, fire and mobs.",
                        "Creative players can still break them.")
                .define("protect_containers", true);
        BREAK_TO_DROP_LOOT = BUILDER
                .comment("If true, a survival player who breaks a loot container WITHOUT sneaking collects their loot into their",
                        "inventory instead (the container stays). Sneaking while breaking falls through to the rules below.",
                        "Breaking takes as long as it normally does; the loot is handed over when the break completes.",
                        "Creative players are unaffected. Applies to chests, barrels and shulker boxes.")
                .define("break_to_drop_loot", false);
        REQUIRE_SNEAK_TO_BREAK = BUILDER
                .comment("Only used when protect_containers is false. If true, survival players must sneak to break a loot",
                        "container (it is then destroyed for everyone); a normal break is refused with a hint.",
                        "This is upstream Lootr's default mode. If false (and protect_containers is false) breaking is vanilla.")
                .define("require_sneak_to_break", false);
        SHOULD_DROP_PLAYER_LOOT = BUILDER
                .comment("If true, when a loot container is actually destroyed by a player, that player's own loot spills at the",
                        "block (rolled first if they had not looted it). Only happens when a break is allowed: creative players, or",
                        "survival players when protect_containers is false. Applies to chests, barrels and shulker boxes.")
                .define("should_drop_player_loot", false);
        BUILDER.pop();

        SPEC = BUILDER.build();
    }

    private static volatile Set<ResourceKey<Level>> whitelistCache = null;
    private static volatile Set<ResourceKey<Level>> blacklistCache = null;
    private static volatile Set<String> tableBlacklistCache = null;
    private static volatile Set<String> modBlacklistCache = null;

    /** Call from the config reload event so edited lists take effect. */
    public static void invalidateCaches() {
        whitelistCache = null;
        blacklistCache = null;
        tableBlacklistCache = null;
        modBlacklistCache = null;
    }

    private static Set<ResourceKey<Level>> parse(List<? extends String> raw) {
        Set<ResourceKey<Level>> out = new HashSet<>();
        for (String s : raw) {
            ResourceLocation id = ResourceLocation.tryParse(s);
            if (id != null) {
                out.add(ResourceKey.create(Registries.DIMENSION, id));
            }
        }
        return out;
    }

    public static boolean isDimensionEnabled(ResourceKey<Level> dimension) {
        Set<ResourceKey<Level>> black = blacklistCache;
        if (black == null) {
            black = blacklistCache = parse(DIMENSION_BLACKLIST.get());
        }
        if (black.contains(dimension)) {
            return false;
        }
        Set<ResourceKey<Level>> white = whitelistCache;
        if (white == null) {
            white = whitelistCache = parse(DIMENSION_WHITELIST.get());
        }
        return white.isEmpty() || white.contains(dimension);
    }

    /**
     * False for a null table (nothing to convert) and for tables the admin
     * blacklisted by exact id or by namespace. Every place that decides
     * "is this a Lootr container" goes through here, so a blacklisted table
     * is left completely vanilla: no per-player loot, no break protection.
     */
    public static boolean isLootTableEnabled(ResourceKey<LootTable> table) {
        if (table == null) {
            return false;
        }
        Set<String> tables = tableBlacklistCache;
        if (tables == null) {
            tables = tableBlacklistCache = new HashSet<>(LOOT_TABLE_BLACKLIST.get());
        }
        Set<String> mods = modBlacklistCache;
        if (mods == null) {
            mods = modBlacklistCache = new HashSet<>(MOD_ID_BLACKLIST.get());
        }
        ResourceLocation id = table.location();
        return !tables.contains(id.toString()) && !mods.contains(id.getNamespace());
    }

    private LootrConfig() {}
}
