plugins {
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.80' apply false
    id 'fabric-loom' version '1.14.3' apply false
}

def javaVersion = 21

allprojects {
    version = "${mod_version}"
    group = "${mod_group_id}"

    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'maven-publish'

    base {
        archivesName = "${mod_id}-${project.name}"
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(javaVersion)
        }
    }

    tasks.withType(JavaCompile).configureEach {
        options.release = javaVersion
    }

    tasks.withType(ProcessResources).configureEach {
        var replaceProperties = [
                minecraft_version             : minecraft_version,
                minecraft_version_range       : minecraft_version_range,
                fabric_minecraft_version_range: fabric_minecraft_version_range,
                neoforge_version              : neoforge_version,
                loader_version_range          : loader_version_range,
                fabric_loader_version         : fabric_loader_version,
                fabric_loader_version_range   : fabric_loader_version_range,
                mod_id                        : mod_id,
                mod_name                      : mod_name,
                mod_license                   : mod_license,
                mod_version                   : mod_version,
                mod_authors                   : mod_authors,
                mod_description               : mod_description,
        ]
        inputs.properties replaceProperties
        filesMatching(['META-INF/neoforge.mods.toml', 'fabric.mod.json', 'pack.mcmeta']) {
            expand replaceProperties + [project: project]
        }
    }

    publishing {
        publications {
            register('mavenJava', MavenPublication) {
                from components.java
            }
        }
        repositories {
            maven {
                url "file://${project.projectDir}/repo"
            }
        }
    }
}
