org.gradle.daemon=true
org.gradle.jvmargs=-Xmx3G

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neoforge_version=21.1.219
loader_version_range=[2,)

neoform_version=1.21.1-20240808.144430

mod_id=lootr_serveronly
mod_name=Lootr (Server-Only)
mod_license=MIT
mod_version=0.1.0
mod_group_id=net.lootr.serveronly
mod_authors=PsycloneTM
mod_description=Server-side-only reimplementation of Lootr's per-player loot containers. Requires no client-side mod.

yarn_mappings=1.21.1+build.3
fabric_loader_version=0.16.5
fabric_loader_version_range=>=0.16.5
fabric_minecraft_version_range=~1.21.1
fabric_api_version=0.116.9+1.21.1

mixin_extras_version=0.5.4
