package net.lootr.serveronly.fabric.registry;

import net.lootr.serveronly.fabric.config.LootrConfig;
import net.lootr.serveronly.mixin.AccessorItemFrame;
import net.minecraft.world.entity.decoration.ItemFrame;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import org.jetbrains.annotations.Nullable;

/**
 * Decides which item frames are "Lootr frames".
 * <p>
 * Every other Lootr container is recognised by something vanilla already put
 * on it: a loot table. A vanilla item frame has none, and nothing else marks
 * a frame as structure-generated. Two tempting shortcuts are both wrong:
 * <ul>
 *   <li>"Every frame holding an item" would let any player duplicate items
 *       out of any other player's base, one hit at a time.</li>
 *   <li>"Every frame that joins the level" cannot tell a structure spawning a
 *       frame from a player placing one.</li>
 * </ul>
 * So a frame is a Lootr frame only if it carries an explicit marker. The
 * marker is a vanilla <b>entity tag</b> (the same string set {@code /tag}
 * edits): it is saved with the entity automatically, needs no attachment,
 * registry entry or client knowledge, and lets an admin mark or unmark a frame
 * by hand:
 * <pre>
 *   /tag @e[type=item_frame,limit=1,sort=nearest] add lootr_serveronly.loot_frame
 * </pre>
 * <p>
 * <b>Automatic marking.</b> Two mixins call into this class at the moment a
 * <i>structure</i> spawns a frame - the one point where "generated by a
 * structure" and "placed by a player" can be told apart. Identical in intent
 * and injection target to the NeoForge side's mixins of the same names -
 * only the package differs:
 * <ul>
 *   <li>{@code MixinStructureTemplate} - frames baked into a structure
 *       template's entity list -> {@link #onStructureFrameSpawned}.</li>
 *   <li>{@code MixinEndCityPiece} - the End City ship's Elytra frame, which
 *       vanilla spawns from code (a data marker), not from the template ->
 *       {@link #onEndCityElytraFrameSpawned}.</li>
 * </ul>
 * Both <b>tag the frame vanilla already created</b>. Upstream Lootr instead
 * swaps in its own {@code LootrItemFrame} entity type, which a vanilla client
 * could not render; keeping the vanilla entity is what keeps this server-only.
 * <p>
 * Consequences worth knowing:
 * <ul>
 *   <li>Only frames generated <i>after</i> this is installed are marked.
 *       Structures already in an existing world are untouched - mark those by
 *       hand with the command above.</li>
 *   <li>The template hook only marks frames placed during <b>world
 *       generation</b>, not frames placed by a structure block, {@code /place}
 *       or a schematic printer. Those are player-driven, and marking them
 *       would let a player print item-duplicating frames.</li>
 * </ul>
 */
public final class ItemFrameMarker {

    /** The entity tag that makes a frame a Lootr frame. */
    public static final String TAG = "lootr_serveronly.loot_frame";

    public static boolean isMarked(ItemFrame frame) {
        return frame.getTags().contains(TAG);
    }

    /** Marks a frame; safe to call repeatedly. */
    public static void mark(ItemFrame frame) {
        frame.addTag(TAG);
    }

    /**
     * Called by {@code MixinStructureTemplate} for every {@link ItemFrame} a
     * structure template is about to add during world generation. The frame is
     * not in the world yet, so nothing else can see it half-configured.
     */
    public static void onStructureFrameSpawned(ItemFrame frame) {
        if (!LootrConfig.isDisabled() && LootrConfig.convertItemFrames() && isEligibleStructureFrame(frame)) {
            mark(frame);
        }
    }

    /**
     * Called by {@code MixinEndCityPiece} for an {@link ItemFrame} the End City
     * piece is about to add. Vanilla sets the Elytra on the frame before
     * spawning it, which is what tells it apart from anything else that piece
     * might spawn.
     */
    public static void onEndCityElytraFrameSpawned(ItemFrame frame) {
        if (!LootrConfig.isDisabled() && LootrConfig.convertElytrasToItemFrames() && frame.getItem().is(Items.ELYTRA)) {
            mark(frame);
        }
    }

    /**
     * Same exclusions upstream applies before converting a structure frame:
     * a fixed frame is static decoration (a datapack/mod builds those on
     * purpose), an invisible frame is a hidden-display trick, and an empty
     * frame has nothing to hand out. Maps are excluded too - copying a map
     * item is rarely what an admin wants from a "loot" frame.
     */
    private static boolean isEligibleStructureFrame(ItemFrame frame) {
        return ineligibleReason(frame) == null;
    }

    /**
     * Why {@code frame} can't be a loot frame, or {@code null} if it can. This
     * is the single source of the eligibility rules: the automatic structure
     * marking uses it, and so do the {@code /lootr frame mark} commands, so a
     * hand-marked frame can't be an item-duplicating fixed/hidden/map frame
     * either.
     */
    @Nullable
    public static String ineligibleReason(ItemFrame frame) {
        if (((AccessorItemFrame) frame).lootr$isFixed()) {
            return "it is a fixed frame";
        }
        if (frame.isInvisible()) {
            return "it is invisible";
        }
        ItemStack framed = frame.getItem();
        if (framed.isEmpty()) {
            return "it is empty";
        }
        if (framed.is(Items.FILLED_MAP) || framed.is(Items.MAP)) {
            return "it holds a map";
        }
        return null;
    }

    /** Removes the marker. Anyone who already took a copy keeps having taken it. */
    public static void unmark(ItemFrame frame) {
        frame.removeTag(TAG);
    }

    /** The chest an Elytra frame becomes under {@code convert_elytras_to_chests}: one table, one Elytra. */
    public static final net.minecraft.resources.ResourceKey<net.minecraft.world.level.storage.loot.LootTable> ELYTRA_CHEST_TABLE =
            net.minecraft.resources.ResourceKey.create(net.minecraft.core.registries.Registries.LOOT_TABLE,
                    net.minecraft.resources.ResourceLocation.fromNamespaceAndPath("lootr_serveronly", "chests/end_city_elytra"));

    /**
     * {@code convert_elytras_to_chests}: replaces the End City Elytra frame with a chest one block below it, facing the
     * way the frame did, holding {@link #ELYTRA_CHEST_TABLE}. The chest has a loot table, so it then loots per player
     * like any other. Frames take priority (as upstream): this does nothing while convert_elytras_to_item_frames is on.
     * Returns true if the chest was placed, in which case the caller must not add the frame.
     */
    public static boolean convertElytraToChest(net.minecraft.world.level.ServerLevelAccessor level, ItemFrame frame) {
        if (LootrConfig.isDisabled() || !LootrConfig.convertElytrasToChests() || LootrConfig.convertElytrasToItemFrames()
                || !frame.getItem().is(Items.ELYTRA)) {
            return false;
        }
        net.minecraft.core.BlockPos chestPos = frame.getPos().below();
        level.setBlock(chestPos, net.minecraft.world.level.block.Blocks.CHEST.defaultBlockState()
                .setValue(net.minecraft.world.level.block.ChestBlock.FACING, frame.getDirection()), 3);
        if (level.getBlockEntity(chestPos) instanceof net.minecraft.world.level.block.entity.RandomizableContainerBlockEntity chest) {
            chest.setLootTable(ELYTRA_CHEST_TABLE, level.getRandom().nextLong());
        }
        return true;
    }

    private ItemFrameMarker() {}
}
